services:
  train_station_service:
    build:
      context: .
    container_name: train_station_service
    env_file:
      - .env
    ports:
      - "8001:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:alpine3.20
    container_name: postgres_service
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - service_data:$PGDATA

volumes:
  service_data:
